version: '3.8'

services:
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - PORT=8080
      - LOG_JSON=false
      - LOG_LEVEL=INFO
    restart: unless-stopped
