FROM golang:1.24-alpine

WORKDIR /app

# Instalar ferramentas de teste
RUN apk add --no-cache git

# Copiar os arquivos necessários
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Executar testes
CMD ["go", "test", "-v"]
